import React from 'react';
import { Eye, Sparkles, Flame, Shield, ArrowRight, Zap, Trophy, Crown, CheckCircle2 } from 'lucide-react';
import { useAuth } from '../context/AuthContext';

export function LandingPage({ onStartPlay, onOpenPricing, onOpenAuth }) {
  const { user } = useAuth();

  return (
    <div className="min-h-screen">
      
      {/* 1. HERO SECTION */}
      <section className="relative pt-16 pb-24 px-4 overflow-hidden">
        {/* Glowing Mesh Orbs */}
        <div className="absolute top-1/4 left-1/2 -translate-x-1/2 -translate-y-1/2 w-96 h-96 bg-brand-purple/20 rounded-full blur-[120px] pointer-events-none" />
        <div className="absolute top-1/3 left-1/3 w-80 h-80 bg-brand-cyan/20 rounded-full blur-[100px] pointer-events-none" />

        <div className="max-w-5xl mx-auto text-center relative z-10">
          
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-white/5 border border-brand-purple/30 text-brand-purple text-xs font-mono font-bold mb-8 animate-bounce">
            <Sparkles className="w-3.5 h-3.5" />
            <span>CAN YOUR EYES BEAT THE ALGORITHM?</span>
          </div>

          <h1 className="text-4xl sm:text-6xl md:text-7xl font-black font-display text-white tracking-tight leading-[1.1] mb-6">
            Spot the <span className="gradient-text">AI Fake.</span> <br />
            Test Your Intuition.
          </h1>

          <p className="text-base sm:text-lg text-slate-300 max-w-2xl mx-auto mb-10 leading-relaxed">
            Two side-by-side images on the exact same subject. One is an authentic human photo; the other is generated by neural diffusion. Can you spot the fake?
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 max-w-md mx-auto mb-16">
            <button
              onClick={onStartPlay}
              className="w-full sm:w-auto px-8 py-4 rounded-xl gradient-btn font-extrabold text-white text-base shadow-xl flex items-center justify-center gap-2 hover:scale-105 transition-transform"
            >
              <span>🎮 Start Playing Free</span>
              <ArrowRight className="w-5 h-5" />
            </button>
            <button
              onClick={onOpenPricing}
              className="w-full sm:w-auto px-6 py-4 rounded-xl glass-card text-slate-200 font-bold text-sm hover:border-brand-purple transition-all"
            >
              💎 Pro Pass ($2.99/mo)
            </button>
          </div>

          {/* Feature Strip Badges */}
          <div className="flex flex-wrap items-center justify-center gap-6 text-xs text-slate-400 font-mono">
            <div className="flex items-center gap-2">
              <span className="text-emerald-400 font-bold">✓</span> 10 Free Daily Rounds
            </div>
            <div className="flex items-center gap-2">
              <span className="text-brand-cyan font-bold">✓</span> Google Gemini 2.0 AI Pairs
            </div>
            <div className="flex items-center gap-2">
              <span className="text-orange-400 font-bold">✓</span> Global Streak Leaderboard
            </div>
            <div className="flex items-center gap-2">
              <span className="text-brand-purple font-bold">✓</span> Zero Sign-Up Required to Play
            </div>
          </div>

        </div>
      </section>

      {/* 2. HOW IT WORKS (3 STEPS) */}
      <section className="py-20 px-4 border-t border-white/5 bg-slate-950/40">
        <div className="max-w-6xl mx-auto">
          
          <div className="text-center mb-16">
            <h2 className="text-3xl font-black font-display text-white mb-3">How To Play</h2>
            <p className="text-sm text-slate-400">Simple rules, infinite challenge.</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            
            <div className="p-8 rounded-2xl glass-card border border-white/10 relative">
              <div className="w-12 h-12 rounded-xl bg-brand-purple/20 border border-brand-purple/40 text-brand-purple font-black text-xl flex items-center justify-center mb-6">
                1
              </div>
              <h3 className="text-xl font-bold font-display text-white mb-2">Inspect Side-by-Side</h3>
              <p className="text-sm text-slate-400 leading-relaxed">
                You're shown two matched images labeled "A" and "B" sharing identical subject themes. Hover to zoom in 4K resolution.
              </p>
            </div>

            <div className="p-8 rounded-2xl glass-card border border-white/10 relative">
              <div className="w-12 h-12 rounded-xl bg-brand-cyan/20 border border-brand-cyan/40 text-brand-cyan font-black text-xl flex items-center justify-center mb-6">
                2
              </div>
              <h3 className="text-xl font-bold font-display text-white mb-2">Click the AI Fake</h3>
              <p className="text-sm text-slate-400 leading-relaxed">
                Trust your instinct or analyze skin pores, reflections, symmetry, and lighting artifacts. Press A or B on your keyboard.
              </p>
            </div>

            <div className="p-8 rounded-2xl glass-card border border-white/10 relative">
              <div className="w-12 h-12 rounded-xl bg-orange-500/20 border border-orange-500/40 text-orange-400 font-black text-xl flex items-center justify-center mb-6">
                3
              </div>
              <h3 className="text-xl font-bold font-display text-white mb-2">Build Your Streak</h3>
              <p className="text-sm text-slate-400 leading-relaxed">
                Unlock instant AI prompt explanations, climb the global top 100 leaderboard, and share your detective streak!
              </p>
            </div>

          </div>

        </div>
      </section>

      {/* 3. PRO PASS SPOTLIGHT */}
      <section className="py-20 px-4">
        <div className="max-w-4xl mx-auto p-8 md:p-12 rounded-3xl glass-panel border border-brand-purple/40 bg-gradient-to-b from-brand-purple/10 to-transparent relative shadow-2xl">
          <div className="flex flex-col md:flex-row items-center justify-between gap-8">
            <div>
              <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-brand-purple/20 border border-brand-purple text-brand-purple text-xs font-bold font-mono mb-3">
                <Crown className="w-3.5 h-3.5" /> PRO DETECTIVE PASS
              </div>
              <h2 className="text-3xl font-black font-display text-white mb-3">
                Unlimited Rounds for Just $2.99/mo
              </h2>
              <ul className="space-y-2 text-sm text-slate-300">
                <li className="flex items-center gap-2">✓ <strong>100% Ad-Free Experience</strong></li>
                <li className="flex items-center gap-2">✓ <strong>Unlimited 24/7 Rounds</strong> (No 10/day limit)</li>
                <li className="flex items-center gap-2">✓ <strong>Per-Category Accuracy Radar Analytics</strong></li>
                <li className="flex items-center gap-2">✓ <strong>Streak Freeze Protection</strong> (Never lose high streak)</li>
              </ul>
            </div>
            <button
              onClick={onOpenPricing}
              className="px-8 py-4 rounded-xl gradient-btn font-black text-white text-base shadow-xl hover:scale-105 transition-transform flex-shrink-0"
            >
              Upgrade for $2.99/mo →
            </button>
          </div>
        </div>
      </section>

    </div>
  );
}
